version: '3.9'

services:
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:  
      - 2717:27017
    volumes:
      - mongo_db:/data/db

  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080
    environment:
      PORT: 8080
      MONGODB_URL: mongodb+srv://miguelfcosta88:miguel1234@sdistdb.sbvckky.mongodb.net/
      DB_NAME: sdist_db
      NAME: Application
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}