version: '3.9'

services:
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:  
      - 2717:27017
    volumes:
      - mongo_db:/data/db

  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080
    environment:
      PORT: 8080
      MONGODB_URL: mongodb+srv://miguelfcosta88:miguel1234@sdistdb.sbvckky.mongodb.net/
      DB_NAME: sdist_db
      NAME: Application
      PROMETHEUS_URL: http://10.2.15.146:30973
    depends_on:
      - mongo_db

  prometheus:
    image: prom/prometheus
    container_name: prometheus_container
    restart: always
    ports:
      - 9090:9090
    volumes:
      - ./SDist/k8s/prometheus.yml:/etc/prometheus/prometheus.yml:ro

volumes:
  mongo_db: {}