apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-kube-prometheus-prometheus
  namespace: sge
data:
  prometheus.yaml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'mongodb-exporter'
        static_configs:
          - targets: ['mongodb-exporter-prometheus-mongodb-exporter.sge:9216']
            labels:
              instance: 'mongodb-exporter'
