apiVersion: apps/v1
kind: Deployment
metadata:
  name: sdist-login-frontend-deployment
  namespace: sge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sdist-login-frontend
  template:
    metadata:
      labels:
        app: sdist-login-frontend
    spec:
      containers:
        - name: sdist-login-frontend
          image: miguelfcosta/login-frontend:latest  
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: login-frontend-service
  namespace: sge
spec:
  selector:
    app: sdist-login-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000 
  type: ClusterIP