apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mongodb-exporter
  namespace: sge
spec:
  selector:
    matchLabels:
      app: mongodb-exporter
  endpoints:
  - port: mongodb-exporter

