apiVersion: apps/v1
kind: Deployment
metadata:
  name: sdist-login-backend-deployment
  namespace: sge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sdist-login-backend
  template:
    metadata:
      labels:
        app: sdist-login-backend
    spec:
      containers:
        - name: sdist-login-backend
          image: miguelfcosta/login-backend:latest 
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: login-backend-service
  namespace: sge
spec:
  selector:
    app: sdist-login-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080 
  type: ClusterIP