apiVersion: v1
kind: Service
metadata:
  name: login-backend-service
  namespace: sge
spec:
  selector:
    app: projeto-sd-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080 
  type: ClusterIP