apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: sge
spec:
  selector:
    app: projeto-sd
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080 
  type: LoadBalancer 