apiVersion: v1
kind: Service
metadata:
  name: login-frontend-service
  namespace: sge
spec:
  selector:
    app: projeto-sd-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP