name: Push to DockerHub

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: miguelfcosta
          password: dckr_pat_ExoRzjrL2xMzK5368c0tA9VaE3k

      - name: Build Docker image
        run: docker build -t miguelfcosta/imagem123 .

      - name: Push Docker image to Docker Hub
        run: docker push miguelfcosta/imagem123