name: Push to DockerHub

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}


      - name: Build Docker image
        run: docker build -t miguelfcosta/projeto-sdist .

      - name: Push Docker image to Docker Hub
        run: docker push miguelfcosta/projeto-sdist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
          context: cluster-context  # Substitua pelo contexto correto do seu cluster
      
      - name: Apply Kubernetes manifests
        run: kubectl apply -f yaml/