name: Push to DockerHub

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Backend Docker image
        run: docker build -t miguelfcosta/login-backend ./backend
  
      - name: Build Frontend Docker image
        run: docker build -t miguelfcosta/login-frontend ./frontend
  
      - name: Push Backend Docker image to Docker Hub
        run: docker push miguelfcosta/login-backend 
  
      - name: Push Frontend Docker image to Docker Hub
        run: docker push miguelfcosta/login-frontend