name: Push to DockerHub

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}


      - name: Build Docker image
        run: docker build -t miguelfcosta/projeto-sdist .

      - name: Push Docker image to Docker Hub
        run: docker push miguelfcosta/projeto-sdist

      - name: Set up kubectl for deployment
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig
          export KUBECONFIG=$(pwd)/kubeconfig
          kubectl config use-context cluster-context
          kubectl apply -f /yaml
 